name: Python Lint
on: [push, pull_request]
permissions:
  contents: write
  pull-requests: write
jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check whether style changes are needed
        id: black
        uses: psf/black@stable
        with:
          options: --check --diff --color --verbose
          src: ./src
        continue-on-error: true
      - name: Format code 
        if: steps.black.outcome == 'failure'
        uses: psf/black@stable
        with:
          options: --verbose
          src: ./src
      - name: Commit and push changes if code was reformatted
        if: steps.black.outcome == 'failure'
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "Black - GitHub Action"
            git config user.email "actions@github.com"
            git add .
            git commit -m "style: auto-format code with Black"
            git push
          fi