name: Prettier
on: [push]
permissions:
  contents: write
  pull-requests: write
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: poll
        run: npm install

      - name: Run Prettier
        id: prettier-check
        working-directory: poll
        run: npx prettier --check .
        continue-on-error: true

      - name: Format code with Prettier
        if: steps.prettier-check.outcome == 'failure'
        working-directory: poll
        run: npx prettier --write .

      - name: Commit formatted code
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "Prettier - GitHub Action"
            git config user.email "actions@github.com"
            git add .
            git commit -m "style: auto-format code with Prettier"
            git push
          fi
